name: "Testing my workflow"
run-name: "${{ github.actor }} running this workflow from ${{ github.ref }}"

on:
  push:

jobs:
  first_echo:
    runs-on: ubuntu-latest

    steps:
      - name: Who
        run: echo "I am ${{ github.actor }}"
     
