name: "Testing my workflow"
run-name: "${{ github.actor }} running this workflow from ${{ github.ref }}"

on:
  push:
  workflow_dispatch: 

jobs:
  first_echo:
    runs-on: ubuntu-latest

    steps:
      - name: Who
        run: echo "I am ${{ github.actor }}"
      - name: brach
        run: echo "this a ${{github.workflow_sha}}"
  second_echo:
     runs-on: ubuntu-latest
     steps:
       - name: fullname
        run: echo "i am Benedict"
     
