name: Testing my workflow
run-name: ${{ github.actor }} running this workflow from ${{ github.ref }}

on:
  push:
  workflow_dispatch:

jobs:
  first_echo:
    runs-on: ubuntu-latest

    steps:
      - name: Who
        run: echo "I am ${{ github.actor }}"

      - name: 'Workflow SHA'
        run: echo "Workflow SHA: ${{ github.workflow_sha }}"

  second_echo:
    runs-on: ubuntu-latest

    steps:
      - name: Full Name
        run: echo "I am Benedict"
